_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 71
                - 79
                - 83
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 71
                - 79
                - 83
            "3":
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.6
            "6": 4.48.2
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
adam_weight_decay:
    value: 0.01
allow_tf32:
    value: false
base_folder:
    value: null
checkpointing_steps:
    value: 500
checkpoints_total_limit:
    value: 2
conditioning_dropout_prob:
    value: 0.1
enable_xformers_memory_efficient_attention:
    value: false
global_batch_size:
    value: 1
gradient_accumulation_steps:
    value: 16
gradient_checkpointing:
    value: false
height:
    value: 576
hub_model_id:
    value: null
hub_token:
    value: null
learning_rate:
    value: 3e-05
local_rank:
    value: -1
logging_dir:
    value: logs
lr_scheduler:
    value: cosine_with_restarts
lr_warmup_steps:
    value: 500
max_grad_norm:
    value: 1
max_train_steps:
    value: 6200
mixed_precision:
    value: fp16
non_ema_revision:
    value: null
num_frames:
    value: 25
num_train_epochs:
    value: 100
num_validation_images:
    value: 1
num_workers:
    value: 8
output_dir:
    value: /sdb5/output_2
per_gpu_batch_size:
    value: 1
pretrain_unet:
    value: null
pretrained_model_name_or_path:
    value: stabilityai/stable-video-diffusion-img2vid
push_to_hub:
    value: false
report_to:
    value: wandb
resume_from_checkpoint:
    value: null
revision:
    value: null
scale_lr:
    value: false
seed:
    value: 12345
use_8bit_adam:
    value: false
use_ema:
    value: false
validation_steps:
    value: 500
video_folder:
    value: /sdb5/data/train/
width:
    value: 1024
